// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdQH55G1k4a-cKV4isXqjhkGNJC6bh96I',
    appId: '1:426301505270:web:0bcba1ff1559a8eff5f6d7',
    messagingSenderId: '426301505270',
    projectId: 'black-markt',
    authDomain: 'black-markt.firebaseapp.com',
    storageBucket: 'black-markt.appspot.com',
    measurementId: 'G-WCGEJTTVPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZHvREb-Cbu2uejsz57IqkLjaSLlHyEew',
    appId: '1:426301505270:android:54602f3076f327d4f5f6d7',
    messagingSenderId: '426301505270',
    projectId: 'black-markt',
    storageBucket: 'black-markt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzHVU2mWiP29x3qxByscJIceKmgFO2Uzw',
    appId: '1:426301505270:ios:25d3ebaff3384fcaf5f6d7',
    messagingSenderId: '426301505270',
    projectId: 'black-markt',
    storageBucket: 'black-markt.appspot.com',
    iosBundleId: 'com.example.blackMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdQH55G1k4a-cKV4isXqjhkGNJC6bh96I',
    appId: '1:426301505270:web:d0d7558426b2ea33f5f6d7',
    messagingSenderId: '426301505270',
    projectId: 'black-markt',
    authDomain: 'black-markt.firebaseapp.com',
    storageBucket: 'black-markt.appspot.com',
    measurementId: 'G-TEPNEQ5663',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzHVU2mWiP29x3qxByscJIceKmgFO2Uzw',
    appId: '1:426301505270:ios:25d3ebaff3384fcaf5f6d7',
    messagingSenderId: '426301505270',
    projectId: 'black-markt',
    storageBucket: 'black-markt.appspot.com',
    iosBundleId: 'com.example.blackMarket',
  );

}